jhipsterdemo-elasticsearch:
  container_name: jhipsterdemo-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/jHipsterDemo/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
jhipsterdemo-postgresql:
  container_name: jhipsterdemo-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/jHipsterDemo/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=jHipsterDemo
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
